# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mage', '0002_base_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='backgrounds',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='essence',
            field=models.IntegerField(choices=[(1, 'Dynamic'), (2, 'Static'), (3, 'Primordial'), (4, 'Questing'), (5, 'Brak')]),
        ),
        migrations.AlterField(
            model_name='base',
            name='traits',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='willpower',
            field=models.PositiveIntegerField(),
        ),
    ]
