# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mage', '0003_auto_20170828_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnocracySpheres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Union', models.CharField(max_length=200, null=True)),
                ('avatar', models.PositiveIntegerField(null=True)),
                ('data', models.IntegerField(null=True)),
                ('dimensional_science', models.IntegerField(null=True, verbose_name='dimensional science')),
                ('entropy', models.IntegerField(null=True)),
                ('forces', models.IntegerField(null=True)),
                ('life', models.IntegerField(null=True)),
                ('matter', models.IntegerField(null=True)),
                ('mind', models.IntegerField(null=True)),
                ('primal_utility', models.IntegerField(null=True, verbose_name='primal utility')),
                ('time', models.IntegerField(null=True)),
                ('affinity_sphere', models.IntegerField(choices=[(1, 'Data'), (2, 'Dimensional Science'), (3, 'Entropy'), (4, 'Forces'), (5, 'Life'), (6, 'Matter'), (7, 'Mind'), (8, 'Primal Utility'), (9, 'Time')], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='abilities',
            name='secondary_abilities',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='spheres',
            name='avatar',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spheres',
            name='tradition',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='traits',
            field=models.TextField(default='Empty', null=True),
        ),
        migrations.AddField(
            model_name='technocracyspheres',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mage.Base'),
        ),
    ]
