# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mage', '0004_auto_20170829_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='essence',
        ),
        migrations.AddField(
            model_name='base',
            name='picture',
            field=models.ImageField(blank=True, default='photos/nophoto.jpg', null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='spheres',
            name='essence',
            field=models.IntegerField(choices=[(1, 'Dynamic'), (2, 'Static'), (3, 'Primordial'), (4, 'Questing'), (5, 'Brak')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technocracyspheres',
            name='essence',
            field=models.IntegerField(choices=[(1, 'Dynamic'), (2, 'Static'), (3, 'Primordial'), (4, 'Questing'), (5, 'Brak')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='base',
            name='backgrounds',
            field=models.TextField(default='Empty', null=True),
        ),
    ]
