# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mage', '0007_auto_20170829_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilities',
            name='academics',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='alertness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='art',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='athletics',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='awareness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='brawl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='computer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='cosmology',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='crafts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='drive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='empathy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='enigmas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='esoterica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='etiquette',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='expression',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='firearms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='intimidation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='investigation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='law',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='leadership',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='martial_arts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='medicine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='meditation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='melee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='occult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='politics',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='research',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='science',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='secondary_abilities',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='stealth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='streetwise',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='subterfuge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='survival',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='technology',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='apperance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='charisma',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='dexterity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='intelligencee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='manipulation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='perception',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='stamina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='wits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='backgrounds',
            field=models.TextField(blank=True, default='Empty', null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='demenor',
            field=models.IntegerField(blank=True, choices=[(1, 'Activist'), (2, 'Benefactor'), (3, 'Contrary'), (4, 'Crusader'), (5, 'Hacker'), (6, 'Idealist'), (7, 'Innovator'), (8, 'Kid'), (9, 'Loner'), (11, 'Machine'), (12, 'Mad Scientist'), (13, 'Martyr'), (14, 'Monster'), (15, 'Prophet'), (16, 'Rogue'), (17, 'Sensualist'), (18, 'Survivor'), (19, 'Traditionalist'), (20, 'Trickster'), (21, 'Visionary')]),
        ),
        migrations.AlterField(
            model_name='base',
            name='nature',
            field=models.IntegerField(blank=True, choices=[(1, 'Activist'), (2, 'Benefactor'), (3, 'Contrary'), (4, 'Crusader'), (5, 'Hacker'), (6, 'Idealist'), (7, 'Innovator'), (8, 'Kid'), (9, 'Loner'), (11, 'Machine'), (12, 'Mad Scientist'), (13, 'Martyr'), (14, 'Monster'), (15, 'Prophet'), (16, 'Rogue'), (17, 'Sensualist'), (18, 'Survivor'), (19, 'Traditionalist'), (20, 'Trickster'), (21, 'Visionary')]),
        ),
        migrations.AlterField(
            model_name='base',
            name='traits',
            field=models.TextField(blank=True, default='Empty', null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='willpower',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='affinity_sphere',
            field=models.IntegerField(blank=True, choices=[(1, 'Correspondence'), (2, 'Entropy'), (3, 'Forces'), (4, 'Life'), (5, 'Matter'), (6, 'Mind'), (7, 'Prime'), (8, 'Spirit'), (9, 'Time')], null=True),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='avatar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='correspondence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='entropy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='essence',
            field=models.IntegerField(blank=True, choices=[(1, 'Dynamic'), (2, 'Static'), (3, 'Primordial'), (4, 'Questing'), (5, 'None')]),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='forces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='life',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='matter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='mind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='prime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='spirit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='tradition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='technocracyspheres',
            name='Union',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='technocracyspheres',
            name='affinity_sphere',
            field=models.IntegerField(blank=True, choices=[(1, 'Data'), (2, 'Dimensional Science'), (3, 'Entropy'), (4, 'Forces'), (5, 'Life'), (6, 'Matter'), (7, 'Mind'), (8, 'Primal Utility'), (9, 'Time')], null=True),
        ),
        migrations.AlterField(
            model_name='technocracyspheres',
            name='avatar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technocracyspheres',
            name='data',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technocracyspheres',
            name='dimensional_science',
            field=models.IntegerField(blank=True, null=True, verbose_name='dimensional science'),
        ),
        migrations.AlterField(
            model_name='technocracyspheres',
            name='entropy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technocracyspheres',
            name='essence',
            field=models.IntegerField(blank=True, choices=[(1, 'Dynamic'), (2, 'Static'), (3, 'Primordial'), (4, 'Questing'), (5, 'None')]),
        ),
        migrations.AlterField(
            model_name='technocracyspheres',
            name='forces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technocracyspheres',
            name='life',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technocracyspheres',
            name='matter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technocracyspheres',
            name='mind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technocracyspheres',
            name='primal_utility',
            field=models.IntegerField(blank=True, null=True, verbose_name='primal utility'),
        ),
        migrations.AlterField(
            model_name='technocracyspheres',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
