# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mage', '0008_auto_20170829_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='is_independent_mage',
        ),
        migrations.AlterField(
            model_name='attributes',
            name='apperance',
            field=models.IntegerField(blank=True, null=True, verbose_name='appearance'),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='intelligencee',
            field=models.IntegerField(blank=True, null=True, verbose_name='intelligence'),
        ),
    ]
