# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mage', '0009_auto_20170830_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abilities',
            old_name='secondary_abilities',
            new_name='secondary_knowledges',
        ),
        migrations.AddField(
            model_name='abilities',
            name='secondary_skills',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='abilities',
            name='secondary_talents',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='chronicle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='apperance',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='appearance'),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='charisma',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='dexterity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='intelligencee',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='intelligence'),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='manipulation',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='perception',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='stamina',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='strength',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='wits',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='chname',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mage.Chronicle', verbose_name='Chronicle name'),
        ),
        migrations.AlterField(
            model_name='base',
            name='player',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
