# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mage', '0011_auto_20170831_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='chname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mage.Chronicle', verbose_name='Chronicle name'),
        ),
    ]
