# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mage', '0013_auto_20170831_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='picture',
            field=models.URLField(default='http://www.petakids.com/wp-content/uploads/2015/11/Cute-Red-Bunny.jpg', max_length=1000),
        ),
    ]
